---
# tasks file for homebrew

- name: Install homebrew
  shell: '/usr/bin/ruby -e "$(curl -fsSL
  https://raw.githubusercontent.com/Homebrew/install/master/install)"'
  args:
    creates: /usr/local/bin/brew

- name: Install personal homebrew tap
  command: brew tap "{{ homebrew_tap }}"
  args:
    creates: "/usr/local/Homebrew/Library/Taps/{{  homebrew_tap
    .split('/')[0] }}/homebrew-{{  homebrew_tap.split('/')[1] }}"

- homebrew:
    name:
      - ansible
      - bash
      - figlet
      - git
      - gnupg-shared-sc
      - htop
      - opensc
      - pyenv
      - pyenv-virtualenv
      - shellcheck
      - stow
      - terraform
      - terraform-docs
      - watch
    state: present
